### ISSUE TITLE
alpha blending on the stack

### ISSUE THREAD

**Issue by rikkertkoppes** [pkrumins/node-png#23]
Pushing multiple semi transparent png buffers on a stack does not obey alpha blending.

Can this be achieved? Or is it omitted by design? If so, why?

**Comment by pkrumins** [comment]
Alpha blending is not supported. Only 1 alpha channel is supported in the A byte of RGBA or BGRA. Combining two different A's are not supported because we don't have this problem at Browserling, which this module was written for.

**Comment by pkrumins** [comment]
Just had an idea: you can manually change the A bytes of the buffer after the images have been pushed to the stack.
