### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by Marak** [pkrumins/node-png#3]
Marak-Squiress-MacBook-Pro:stackvm maraksquires$ sudo npm install png
npm info it worked if it ends with ok
npm info using npm@0.2.10
npm info using node@v0.3.1
npm ERR! sudon't! 
npm ERR! sudon't! Running npm as root is not recommended!
npm ERR! sudon't! Seriously, don't do this!
npm ERR! sudon't!
npm info preinstall png@1.0.3
npm info install png@1.0.3
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/maraksquires/.node_libraries 
Checking for node prefix                 : ok /usr/local 
Checking for library png                 : not found 
'configure' finished successfully (0.119s)
Waf: Entering directory `/usr/local/lib/node/.npm/png/1.0.3/package/build'
[2/7] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/7] cxx: src/png.cpp -> build/default/src/png_1.o
In file included from ../src/png_encoder.cpp:3:
In file included from ../src/png.cpp:4:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png.cpp:4:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
../src/png.cpp: In member function ‘v8::Handle<v8::Value> Png::PngEncodeSync()’:
../src/png.cpp:31: error: ‘class node::Buffer’ has no member named ‘data’
../src/png.cpp:35: error: ‘class node::Buffer’ has no member named ‘data’
../src/png.cpp: In static member function ‘static int Png::EIO_PngEncode(eio_req*)’:
../src/png.cpp:110: error: ‘class node::Buffer’ has no member named ‘data’
../src/png.cpp: In static member function ‘static int Png::EIO_PngEncodeAfter(eio_req*)’:
../src/png.cpp:145: error: ‘class node::Buffer’ has no member named ‘data’
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
../src/png_encoder.cpp:7: error: variable or field ‘png_chunk_producer’ declared void
../src/png_encoder.cpp:7: error: ‘png_structp’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_bytep’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_size_t’ was not declared in this scope
Waf: Leaving directory`/usr/local/lib/node/.npm/png/1.0.3/package/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx png_encoder.cpp -> png_encoder_1.o}
 -> task failed (err #1): 
    {task: cxx png.cpp -> png_1.o}
npm info png@1.0.3 Failed to exec install script
npm ERR! install failed Error: png@1.0.3 install: `node-waf configure build`
npm ERR! install failed `sh` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.10/package/lib/utils/exec.js:24:18)
npm ERR! install failed     at ChildProcess.emit (events.js:27:15)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:169:12)
npm info install failed rollback
npm info not installed png,1.0.3
npm info install failed rolled back
npm ERR! Error: png@1.0.3 install: `node-waf configure build`
npm ERR! `sh` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.10/package/lib/utils/exec.js:24:18)
npm ERR!     at ChildProcess.emit (events.js:27:15)
npm ERR!     at ChildProcess.onexit (child_process.js:169:12)
npm ERR! 
npm ERR! Failed at the png@1.0.3 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There may be additional logging output above.
npm not ok
Marak-Squiress-MacBook-Pro:stackvm maraksquires$

**Comment by pkrumins** [comment]
you're missing libpng! get it installed on your mac!

**Comment by pkrumins** [comment]
i am closing this issue as no further comments were received and it seems that the problem was that libpng was not installed.

**Comment by harcek** [comment]
Hello,
I came across the same problem as Marak did.
Configuration of my machine is:
Darwin 10.7.0 / OS X 10.6.7
node version 0.5.0-pre
npm version 1.0.1rc2

paths
/Users/daniel/.npm/ (npm)
/usr/local/lib/node (nodepath)
/opt/local/lib (location where is libpng originally installed on my machine)
/opt/local/include/libpng14 (location where are libpng includes placed originally on my machine)

First I had also 
Checking for library png : not found 
so I found the wscript for module, checked where does it expect the location and tried to modify

~/.npm/png/2.0.0/package/wscript

<pre>
  conf.check(lib='png', libpath=['/lib', '/usr/lib', '/usr/local/lib', '/usr/local/libpng/lib', '/usr/local/pkg/libpng-1.4.1/lib'])
=>
  conf.check(lib='png', libpath=['/lib', '/usr/lib', '/usr/local/lib', '/usr/local/libpng/lib', '/usr/local/pkg/libpng-1.4.1/lib', '/opt/local/lib'])
</pre>


But it did not help, so I simply made symlinks to one of the expected locations

<pre>
[2011-06-07 15:30:28] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng.a /usr/local/lib/libpng.a
[2011-06-07 15:30:40] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng.dylib /usr/local/lib/libpng.dylib
[2011-06-07 15:30:54] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng.la /usr/local/lib/libpng.la
[2011-06-07 15:31:04] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng14.14.dylib /usr/local/lib/libpng14.14.dylib
[2011-06-07 15:31:42] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng14.a /usr/local/lib/libpng14.a
[2011-06-07 15:32:07] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng14.dylib /usr/local/lib/libpng14.dylib
[2011-06-07 15:32:17] daniel@domore-mac:/opt/local/lib$sudo ln -s /opt/local/lib/libpng14.la /usr/local/lib/libpng14.la
</pre>


This helped of course, now the configure does know the lib. But I still have problems compiling the module.

<pre>
[2011-06-10 15:49:43] daniel@domore-mac:~$sudo npm install png
> png@2.0.0 install /Users/daniel/node_modules/png
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node 
Checking for node prefix                 : ok /usr/local 
Checking for library png                 : yes 
'configure' finished successfully (0.341s)
Waf: Entering directory `/Users/daniel/node_modules/png/build'
[1/8] cxx: src/common.cpp -> build/default/src/common_1.o
[2/8] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/default/src/png_1.o
[4/8] cxx: src/fixed_png_stack.cpp -> build/default/src/fixed_png_stack_1.o
In file included from ../src/fixed_png_stack.cpp:3:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png.cpp:4:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png.cpp:4:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
../src/png_encoder.cpp:7: error: variable or field ‘png_chunk_producer’ declared void
../src/png_encoder.cpp:7: error: ‘png_structp’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_bytep’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_size_t’ was not declared in this scope
In file included from ../src/fixed_png_stack.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
Waf: Leaving directory `/Users/daniel/node_modules/png/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx png_encoder.cpp -> png_encoder_1.o}
 -> task failed (err #1): 
    {task: cxx png.cpp -> png_1.o}
 -> task failed (err #1): 
    {task: cxx fixed_png_stack.cpp -> fixed_png_stack_1.o}
npm ERR! error installing png@2.0.0 Error: png@2.0.0 install: `node-waf configure build`
npm ERR! error installing png@2.0.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing png@2.0.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing png@2.0.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing png@2.0.0     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! png@2.0.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the png@2.0.0 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "png"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/daniel/npm-debug.log
npm not ok
</pre>


So I basically tried to do the same thing with includes, as I did with lib - symlink it from /opt/local/include/libpng14 to 
- /usr/local/include/libpng14
- /usr/local/include/libpng
- /usr/include/libpng14
- /usr/include/libpng

Also I tried to add additional include paths for the compiler headers inside the module wscript in build function definition

<pre>
  obj.cxxflags = ["-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE", "-I/usr/local/include/libpng"]
</pre>

But did not help also. [somehow I have a feeling that my changes in wscript are not taken into account, probably the configuration process does not use that one]
Now I runned out of any ideas how to continue. If you would be so kind and check this issue, maybe I am just missing something. Thanks in advance.

P.S.: npm-debug.log entry of the build process follows (I did not find anything relevant inside, but as I said, I am probably missing something important :))

<pre>
info it worked if it ends with ok
verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'png' ]
info using npm@1.0.1rc2
info using node@v0.5.0-pre
verbose config file /Users/daniel/.npmrc
verbose config file /usr/local/etc/npmrc
info into /Users/daniel [ 'png' ]
verbose cache add [ 'png', null ]
info addNamed [ 'png', '' ]
verbose addNamed [ null, '' ]
verbose GET png
verbose raw, before any munging png
verbose url resolving [ 'http://registry.npmjs.org/', './png' ]
verbose url resolved http://registry.npmjs.org/png
verbose url parsed { protocol: 'http:',
verbose url parsed   slashes: true,
verbose url parsed   host: 'registry.npmjs.org',
verbose url parsed   hostname: 'registry.npmjs.org',
verbose url parsed   pathname: '/png',
verbose url parsed   href: 'http://registry.npmjs.org/png' }
verbose etag "624SJNWMIAYSM230NZT7279P7"
verbose response http://registry.npmjs.org/png
silly get cb [ 304,
silly get cb   { server: 'CouchDB/1.1.0 (Erlang OTP/R14B)',
silly get cb     etag: '"624SJNWMIAYSM230NZT7279P7"',
silly get cb     date: 'Fri, 10 Jun 2011 13:25:56 GMT',
silly get cb     'content-length': '0' } ]
verbose etag png from cache
verbose GET png/2.0.0
verbose raw, before any munging png/2.0.0
verbose url resolving [ 'http://registry.npmjs.org/', './png/2.0.0' ]
verbose url resolved http://registry.npmjs.org/png/2.0.0
verbose url parsed { protocol: 'http:',
verbose url parsed   slashes: true,
verbose url parsed   host: 'registry.npmjs.org',
verbose url parsed   hostname: 'registry.npmjs.org',
verbose url parsed   pathname: '/png/2.0.0',
verbose url parsed   href: 'http://registry.npmjs.org/png/2.0.0' }
verbose etag "624SJNWMIAYSM230NZT7279P7"
verbose response http://registry.npmjs.org/png/2.0.0
silly get cb [ 304,
silly get cb   { server: 'CouchDB/1.1.0 (Erlang OTP/R14B)',
silly get cb     etag: '"624SJNWMIAYSM230NZT7279P7"',
silly get cb     date: 'Fri, 10 Jun 2011 13:25:56 GMT',
silly get cb     'content-length': '0' } ]
verbose etag png/2.0.0 from cache
verbose bin dist [ null,
verbose bin dist   { tarball: 'http://registry.npmjs.org/png/-/png-2.0.0.tgz' } ]
silly resolved [ { name: 'png',
silly resolved     version: '2.0.0',
silly resolved     main: 'png',
silly resolved     description: 'A C++ module for node-js that converts an RGB and RGBA buffers to PNG images (in memory).',
silly resolved     keywords: [ 'png', 'rgb', 'rgba', 'image', 'picture' ],
silly resolved     maintainers: 
silly resolved      [ { name: 'Peteris Krumins',
silly resolved          email: 'peteris.krumins@gmail.com',
silly resolved          web: 'http://www.catonmat.net',
silly resolved          twitter: 'pkrumins' } ],
silly resolved     licenses: [ { type: 'MIT' } ],
silly resolved     repositories: 
silly resolved      [ { type: 'git',
silly resolved          url: 'http://github.com/pkrumins/node-png.git' } ],
silly resolved     directories: { examples: 'examples', src: 'src' },
silly resolved     engines: { node: '>=0.3.0' },
silly resolved     scripts: { install: 'node-waf configure build' },
silly resolved     _id: 'png@2.0.0',
silly resolved     _nodeSupported: false,
silly resolved     _npmVersion: '0.2.5-1',
silly resolved     _nodeVersion: 'v0.2.4',
silly resolved     dist: { tarball: 'http://registry.npmjs.org/png/-/png-2.0.0.tgz' } } ]
info (resolved) into /Users/daniel [ 'png@2.0.0' ]
info installOne png@2.0.0
silly testEngine { name: 'png',
silly testEngine   version: '2.0.0',
silly testEngine   main: 'png',
silly testEngine   description: 'A C++ module for node-js that converts an RGB and RGBA buffers to PNG images (in memory).',
silly testEngine   keywords: [ 'png', 'rgb', 'rgba', 'image', 'picture' ],
silly testEngine   maintainers: 
silly testEngine    [ { name: 'Peteris Krumins',
silly testEngine        email: 'peteris.krumins@gmail.com',
silly testEngine        url: 'http://www.catonmat.net' } ],
silly testEngine   licenses: [ { type: 'MIT' } ],
silly testEngine   repositories: 
silly testEngine    [ { type: 'git',
silly testEngine        url: 'http://github.com/pkrumins/node-png.git' } ],
silly testEngine   directories: { examples: 'examples', src: 'src' },
silly testEngine   engines: { node: '>=0.3.0' },
silly testEngine   scripts: { install: 'node-waf configure build' },
silly testEngine   _id: 'png@2.0.0',
silly testEngine   _engineSupported: true,
silly testEngine   _npmVersion: '1.0.1rc2',
silly testEngine   _nodeVersion: 'v0.5.0-pre',
silly testEngine   _defaultsLoaded: true,
silly testEngine   dist: { shasum: 'd2907064700ad65c79a417e4e5cd6f07b6726410' } }
verbose caching /Users/daniel/.npm/png/2.0.0/package.json
verbose mkdir done: /Users/daniel/node_modules/___png.npm
verbose unpack_ uid, gid [ 0, 0 ]
verbose unpackTarget /Users/daniel/node_modules/png
verbose success gzip "--decompress" "--stdout" "/Users/daniel/.npm/png/2.0.0/package.tgz"
verbose success tar "-mvxpf" "-" "--no-same-owner" "-C" "/Users/daniel/node_modules/___png.npm"
verbose gunzed /Users/daniel/node_modules/___png.npm/package
verbose rm'ed /Users/daniel/node_modules/png
verbose renamed [ '/Users/daniel/node_modules/___png.npm/package',
verbose renamed   '/Users/daniel/node_modules/png' ]
verbose rm'ed /Users/daniel/node_modules/___png.npm
verbose has wscript [ undefined,
verbose has wscript   { file: '/Users/daniel/node_modules/png/package.json',
verbose has wscript     wscript: 
verbose has wscript      [ '\ndef configure',
verbose has wscript        '\n',
verbose has wscript        index: 188,
verbose has wscript        input: 'import Options\nfrom os import unlink, symlink, popen\nfrom os.path import exists \n\nsrcdir = "."\nblddir = "build"\nVERSION = "0.0.1"\n\ndef set_options(opt):\n  opt.tool_options("compiler_cxx")\n\ndef configure(conf):\n  conf.check_tool("compiler_cxx")\n  conf.check_tool("node_addon")\n  conf.check(lib=\'png\', libpath=[\'/lib\', \'/usr/lib\', \'/usr/local/lib\', \'/usr/local/libpng/lib\', \'/usr/local/pkg/libpng-1.4.1/lib\'])\n\ndef build(bld):\n  obj = bld.new_task_gen("cxx", "shlib", "node_addon")\n  obj.target = "png"\n  obj.source = "src/common.cpp src/png_encoder.cpp src/png.cpp src/fixed_png_stack.cpp src/dynamic_png_stack.cpp src/module.cpp src/buffer_compat.cpp"\n  obj.uselib = "PNG"\n  obj.cxxflags = ["-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE"]\n\ndef shutdown():\n  if Options.commands[\'clean\']:\n    if exists(\'png.node\'): unlink(\'png.node\')\n  else:\n    if exists(\'build/default/png.node\') and not exists(\'png.node\'):\n      symlink(\'build/default/png.node\', \'png.node\')\n\n' ] } ]
silly testEngine { name: 'png',
silly testEngine   version: '2.0.0',
silly testEngine   main: 'png',
silly testEngine   description: 'A C++ module for node-js that converts an RGB and RGBA buffers to PNG images (in memory).',
silly testEngine   keywords: [ 'png', 'rgb', 'rgba', 'image', 'picture' ],
silly testEngine   maintainers: 
silly testEngine    [ { name: 'Peteris Krumins',
silly testEngine        email: 'peteris.krumins@gmail.com',
silly testEngine        url: 'http://www.catonmat.net' } ],
silly testEngine   licenses: [ { type: 'MIT' } ],
silly testEngine   repositories: 
silly testEngine    [ { type: 'git',
silly testEngine        url: 'http://github.com/pkrumins/node-png.git' } ],
silly testEngine   directories: { examples: 'examples', src: 'src' },
silly testEngine   engines: { node: '>=0.3.0' },
silly testEngine   scripts: { install: 'node-waf configure build' },
silly testEngine   _id: 'png@2.0.0',
silly testEngine   _engineSupported: true,
silly testEngine   _npmVersion: '1.0.1rc2',
silly testEngine   _nodeVersion: 'v0.5.0-pre',
silly testEngine   _defaultsLoaded: true }
verbose caching /Users/daniel/node_modules/png/package.json
verbose loadDefaults png@2.0.0
info into /Users/daniel/node_modules/png []
silly resolved []
info (resolved) into /Users/daniel/node_modules/png []
verbose about to build /Users/daniel/node_modules/png
info build /Users/daniel/node_modules/png
verbose from cache /Users/daniel/node_modules/png/package.json
info preinstall png@2.0.0
verbose linkStuff [ false, false, false, '/Users/daniel/node_modules' ]
info linkStuff png@2.0.0
info linkBins png@2.0.0
info linkMans png@2.0.0
info rebuildBundles png@2.0.0
verbose rebuildBundles [ { stack: [Getter/Setter],
verbose rebuildBundles     arguments: undefined,
verbose rebuildBundles     type: undefined,
verbose rebuildBundles     message: 'ENOENT, No such file or directory',
verbose rebuildBundles     errno: 2,
verbose rebuildBundles     code: 'ENOENT' },
verbose rebuildBundles   undefined ]
info install png@2.0.0
verbose unsafe-perm in lifecycle false
verbose Setting uid from 0 nobody
verbose stack at uid setting Error
verbose stack at uid setting     at exec (/usr/local/lib/node_modules/npm/lib/utils/exec.js:35:17)
verbose stack at uid setting     at Array.0 (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:102:5)
verbose stack at uid setting     at EventEmitter._tickCallback (node.js:170:26)
silly exec sh "-c" "node-waf configure build"
info png@2.0.0 Failed to exec install script
ERR! error installing png@2.0.0 { stack: [Getter/Setter],
ERR! error installing png@2.0.0   arguments: undefined,
ERR! error installing png@2.0.0   type: undefined,
ERR! error installing png@2.0.0   message: 'png@2.0.0 install: `node-waf configure build`\n`sh "-c" "node-waf configure build"` failed with 1',
ERR! error installing png@2.0.0   errno: {},
ERR! error installing png@2.0.0   pkgid: 'png@2.0.0',
ERR! error installing png@2.0.0   stage: 'install',
ERR! error installing png@2.0.0   script: 'node-waf configure build',
ERR! error installing png@2.0.0   pkgname: 'png' }
verbose from cache /Users/daniel/node_modules/png/package.json
info preuninstall png@2.0.0
info uninstall png@2.0.0
info unbuild png@2.0.0 [ false,
info unbuild png@2.0.0   '/usr/local/node_modules',
info unbuild png@2.0.0   '/Users/daniel/node_modules' ]
info postuninstall png@2.0.0
info installOne cb png@2.0.0
ERR! png@2.0.0 install: `node-waf configure build`
ERR! `sh "-c" "node-waf configure build"` failed with 1
ERR! 
ERR! Failed at the png@2.0.0 install script.
ERR! This is most likely a problem with the png package,
ERR! not with npm itself.
ERR! Tell the author that this fails on your system:
ERR!     node-waf configure build
ERR! You can get their info via:
ERR!     npm owner ls png
ERR! There is likely additional logging output above.
ERR! 
ERR! System Darwin 10.7.0
ERR! command "node" "/usr/local/bin/npm" "install" "png"
verbose exit [ 1, true ]
</pre>

**Comment by harcek** [comment]
I decided to try not to install / compile via npm but to compile module downloaded via npm manually.
So I navigated to

<pre>
/Users/username/.npm/png/2.0.0/package
</pre>


and runned

<pre>
sudo node-waf configure build
</pre>

to build the module

This time all runned smooth.

<pre>
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node 
Checking for node prefix                 : ok /usr/local 
Checking for library png                 : yes 
'configure' finished successfully (1.916s)
Waf: Entering directory `/Users/daniel/.npm/png/2.0.0/package/build'
[1/8] cxx: src/common.cpp -> build/default/src/common_1.o
[2/8] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/default/src/png_1.o
[4/8] cxx: src/fixed_png_stack.cpp -> build/default/src/fixed_png_stack_1.o
[5/8] cxx: src/dynamic_png_stack.cpp -> build/default/src/dynamic_png_stack_1.o
[6/8] cxx: src/module.cpp -> build/default/src/module_1.o
[7/8] cxx: src/buffer_compat.cpp -> build/default/src/buffer_compat_1.o
[8/8] cxx_link: build/default/src/common_1.o build/default/src/png_encoder_1.o build/default/src/png_1.o build/default/src/fixed_png_stack_1.o build/default/src/dynamic_png_stack_1.o build/default/src/module_1.o build/default/src/buffer_compat_1.o -> build/default/png.node
ld: warning: directory '/lib' following -L not found
ld: warning: directory '/usr/local/libpng/lib' following -L not found
ld: warning: directory '/usr/local/pkg/libpng-1.4.1/lib' following -L not found
Waf: Leaving directory `/Users/daniel/.npm/png/2.0.0/package/build'
'build' finished successfully (2.414s)
</pre>


So I just made a symlink of the resulting node.png into my NODE_PATH

<pre>
ln -s /Users/daniel/.npm/png/2.0.0/package/png.node /usr/local/lib/node/png.node
</pre>

And all runned fine.
You can check you node path via shell by typing

<pre>
bash-3.2# node
> require.paths
[ '/usr/local/lib/node', '/Users/daniel/.node_modules', '/Users/daniel/.node_libraries', '/usr/local/lib/node' ]
</pre>


Note: 
I later deleted produced `png.node` file and tried to run the

<pre>
sudo npm install png
</pre>

procedure from different locations in terminal, but it did not work (I also tried to install it with `-g` global option). Either I got error response or in some cases I did not get back any output (I was navigated inside /Users/username/.npm/png/2.0.0 and deeper). At the end, I decided not to spend time on trying to make it work through `npm install`.
