### ISSUE TITLE
Does not compile against node 0.3.2

### ISSUE THREAD

**Issue by nanodocumet** [pkrumins/node-png#4]
I think the reason is due to the change of the Buffer API.

Check these files:
https://github.com/ry/node/blob/v0.1.96/src/node_buffer.h

https://github.com/ry/node/blob/v0.3.2/src/node_buffer.h

One of the API calls that node-png does is data->data() (examples in line 31, link below), which is no longer available.
https://github.com/pkrumins/node-png/blob/master/src/png.cpp#L31

I have tried to change the .cc file myself with no luck into the new API, which I think should be Data(v8::Handlev8::Object obj).

Can you give me a hint on how to do that?

Thanks.

**Comment by pkrumins** [comment]
just noticed this issue. it does work now!
