### ISSUE TITLE
write png image from str (opencv and thrift)

### ISSUE THREAD

**Issue by matiasfha** [pkrumins/node-png#5]
(sorry for my english).. 
Hi! .. i have a little app in c++ that capture images and send it to a 
nodejs server using thrift [1] .. 
The image data is converted to PNG data in the c++ side and sended to 
the nodejs using thrift, the data is received like str .. 
In the server.js i write the methods to read the data and put into a 
Buffer, then using node-png i try to write the image to disc, but i 
can't see the image, i  only have a dirty image like a TV when the 
signal is bad. 
This is my nodejs server (with thrift). 

```
 var Png = require('png').Png; 
 var fs = require('fs'); 
 var sys = require('sys'); 
 var thrift = require('thrift'); 
 var Buffer = require('buffer').Buffer; 
 var ImageService = require('./ImageService.js'), 
    ttypes = require('./service_types.js'); 
 var indice=0; 
 var receiveImage = function(image,success){ 
     console.log("Recibida: "); 
     var rgb = new Buffer(image.data); 
     var png = new Png(rgb,image.width,image.height,'rgb'); 
     png.encode(function(data,error){ 
          if(error){ 
               console.log('Error: '+error.toString()); 
               process.exit(1); 
          }else{ 
              fs.writeFileSync('png'+indice +'.png',data.toString('binary'),'binary'); 
         } 
    }); 
   success(true); 
 }  
 var server = thrift.createServer(ImageService,{ 
     receiveImage: receiveImage 
 }); 

 server.listen(9090,function(){ 
    console.log("Escuchando...\n"); 
 });
```

Any idea???
thanks a lot

[1] https://github.com/wadey/node-thrift 
http://thrift.apache.org/

**Comment by pkrumins** [comment]
Hi. I don't really know. The only problem I can think of is that the data that you have isn't really RGB. You should find another program that converts RGB data to images to verify that your data is really an image. I use node-png without problems with correct data.
