### ISSUE TITLE
(Suggestion) Parsing PNG data

### ISSUE THREAD

**Issue by FireyFly** [pkrumins/node-png#6]
It'd be great if this module also had the possibility to turn a PNG buffer into a raw pixel buffer, i.e. the inverse operation of what the module currently does. Surely libpng must provide this kind of functionality...

**Comment by pkrumins** [comment]
I'd gladly accept a patch for that if someone wrote it. I am not interested in implementing it myself.

**Comment by FireyFly** [comment]
Oh, okay. I might give it a try some day; I'll make sure to do a pull request if I do.
