### ISSUE TITLE
Cannot install on node 0.4.8

### ISSUE THREAD

**Issue by BrazilianJoe** [pkrumins/node-png#7]
npm info install png@2.0.0
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.4.8 
Checking for library png                 : not found 
'configure' finished successfully (0.755s)
Waf: Entering directory `/usr/local/lib/node/.npm/png/2.0.0/package/build'
[1/8] cxx: src/common.cpp -> build/default/src/common_1.o
[2/8] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/default/src/png_1.o
[4/8] cxx: src/fixed_png_stack.cpp -> build/default/src/fixed_png_stack_1.o
In file included from ../src/fixed_png_stack.cpp:3:
../src/png_encoder.h:4:17: error: png.h: No such file or directoryIn file included from ../src/png_encoder.cpp:3
:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png.cpp:4:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
../src/png_encoder.cpp:7: error: variable or field ‘png_chunk_producer’ declared void
../src/png_encoder.cpp:7: error: ‘png_structp’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_bytep’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_size_t’ was not declared in this scope
In file included from ../src/png.cpp:4:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
In file included from ../src/fixed_png_stack.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
Waf: Leaving directory`/usr/local/lib/node/.npm/png/2.0.0/package/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx png_encoder.cpp -> png_encoder_1.o}
 -> task failed (err #1): 
    {task: cxx png.cpp -> png_1.o}
 -> task failed (err #1): 
    {task: cxx fixed_png_stack.cpp -> fixed_png_stack_1.o}
npm info png@2.0.0 Failed to exec install script
npm ERR! install failed Error: png@2.0.0 install: `node-waf configure build`
npm ERR! install failed `sh "-c" "node-waf configure build"` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:192:12)
npm info install failed rollback
npm info uninstall [ 'png@2.0.0' ]
npm info preuninstall png@2.0.0
npm info uninstall png@2.0.0
npm info auto-deactive not symlink
npm info postuninstall png@2.0.0
npm info uninstall png@2.0.0 complete
npm info install failed rolled back
npm ERR! Error: png@2.0.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! 
npm ERR! Failed at the png@2.0.0 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.0.0
npm ERR! argv { remain: [ 'png' ],
npm ERR! argv   cooked: [ 'install', 'png' ],
npm ERR! argv   original: [ 'install', 'png' ] }
npm not ok

**Comment by pkrumins** [comment]
Hi. You should make sure libpng (together with headers) is installed. Whenever you see errors like `../src/png_encoder.h:4:17: error: png.h: No such file or directory` it means the header files are missing, so something isn't installed. So try to to `sudo apt-get install libpng-devel` or whatever the right package is for you distribution. Alternatively you can compile libpng yourself, and add the path to header files in `wscript` file in line where it says `conf.check(lib='png', libpath=['/lib', '/usr/lib', '/usr/local/lib', '/usr/local/libpng/lib', '/usr/local/pkg/libpng-1.4.1/lib'])`.

**Comment by BrazilianJoe** [comment]
I am on Mac OS X (though I use Ubuntu too).
Mac OS X ships with libpng. The header is installed with X11 and is located at /usr/X11/include, but it is not being picked up. I have never edited a npm formula, but my feeling is that this path-finding stuff should go on npm itself, not specific formulas, since it's a system-wide header.
What do you think? Should I open an issue with the npm folks?

**Comment by BrazilianJoe** [comment]
Hummm the node-waf configure build stuff is getting lost on the png.cpp includes.

You are including the files using quotes, it should find the headers in the same folder as your source, but somehow is doesn't. Your source has png_encoder.h, but it's not being found by the code. I don't know if it's a npm bug, or if npm moved to a different algorithm and caused your formula to bit-rot as a result...

**Comment by BrazilianJoe** [comment]
I have added '/usr/X11/include' to the conf.check line but it still did not recognize the png header file. If you can shed any light on the subject I'd be very grateful.

**Comment by pkrumins** [comment]
Hi. It usually works. I don't know what's going on in your case. I don't think it's npm issue. Can you try compiling libpng yourself and then installing it to something like `/home/you/installs/libpng` and then add the `home/hou/installs/libpns/include` to conf.check line?

**Comment by kpricorn** [comment]
Hey, I had the same issue as BrazilianJoe described above. The following steps solved my problem (on os X).
- Original wscript file

```
$ node-waf configure
<snip>
Checking for library png                 : not found 
```
- After adding '/usr/X11/lib' to conf.check

```
$ node-waf configure
<snip>
Checking for library png                 : yes 
```
- But build still fails

```
$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/sdecaste/local/brew/Cellar/node/0.4.9 
Checking for library png                 : yes 
'configure' finished successfully (0.147s)
Waf: Entering directory `/Users/sdecaste/shared/devel/node-png/build'
[2/8] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/default/src/png_1.o
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png.cpp:4:
../src/png_encoder.h:4:17: error: png.h: No such file or directory
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
../src/png_encoder.cpp:7: error: variable or field ‘png_chunk_producer’ declared void
../src/png_encoder.cpp:7: error: ‘png_structp’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_bytep’ was not declared in this scope
../src/png_encoder.cpp:7: error: ‘png_size_t’ was not declared in this scope
In file included from ../src/png.cpp:4:
../src/png_encoder.h:19: error: ‘png_structp’ has not been declared
../src/png_encoder.h:19: error: ‘png_bytep’ has not been declared
../src/png_encoder.h:19: error: ‘png_size_t’ has not been declared
Waf: Leaving directory `/Users/sdecaste/shared/devel/node-png/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx png_encoder.cpp -> png_encoder_1.o}
 -> task failed (err #1): 
    {task: cxx png.cpp -> png_1.o}
```
- -I flag

I had to add a `"-I/usr/X11/include"` flag entry to obj.cxxflags

```
def build(bld):
  <snip>
  obj.cxxflags = ["-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE", "-I/usr/X11/include"]

```

```
$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/sdecaste/local/brew/Cellar/node/0.4.9 
Checking for library png                 : yes 
'configure' finished successfully (0.129s)
Waf: Entering directory `/Users/sdecaste/shared/devel/node-png/build'
[1/8] cxx: src/common.cpp -> build/default/src/common_1.o
[2/8] cxx: src/png_encoder.cpp -> build/default/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/default/src/png_1.o
[4/8] cxx: src/fixed_png_stack.cpp -> build/default/src/fixed_png_stack_1.o
[5/8] cxx: src/dynamic_png_stack.cpp -> build/default/src/dynamic_png_stack_1.o
[6/8] cxx: src/module.cpp -> build/default/src/module_1.o
[7/8] cxx: src/buffer_compat.cpp -> build/default/src/buffer_compat_1.o
Waf: Leaving directory `/Users/sdecaste/shared/devel/node-png/build'
'build' finished successfully (1.005s)
```

This is probably not a generic solution, but it may help to pinpoint the problem.

**Comment by pkrumins** [comment]
awesome!

**Comment by BrazilianJoe** [comment]
awesome ^ 2! Will we see a new release of node-png? I would like to have as few forks as possible.

**Comment by pkrumins** [comment]
I have not planned any new releases of node-png. It works precisely the way I need.
