### ISSUE TITLE
16 big (grayscale) PNGs?

### ISSUE THREAD

**Issue by bingomanatee** [pkrumins/node-png#8]
Can you use your library to do 16 bit (grayscale) PNGS? thanks -  Dave

**Comment by pkrumins** [comment]
Sorry, it works only for 24 and 32 bits: RGB, RGBA, BGR and BGRA.

**Comment by bingomanatee** [comment]
I would gladly pay for a grayscale version - interested?

**Comment by f00li5h** [comment]
=$_$=

**Comment by pkrumins** [comment]
Dave, I'm interested! Email me at peteris.krumins@gmail.com. I can't promise I'll agree to add. It depends on how easy or complex it is.

**Comment by bingomanatee** [comment]
NM - turns out I need RAW data for my purposes anyway :D

**Comment by pkrumins** [comment]
Alright. ;)
